loki:
  image:
    repository: grafana/loki
    tag: 2.9.0

  config:
    auth_enabled: false
    server:
      http_listen_port: 3100
    schema_config:
      configs:
        - from: 2023-01-01
          store: boltdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb:
        directory: /data/loki/index
      filesystem:
        directory: /data/loki/chunks

  service:
    type: ClusterIP
    port: 3100

replicaCount: 2

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

persistence:
  enabled: true
  storageClassName: gp3-csi
  accessModes:
    - ReadWriteOnce
  size: 10Gi
