apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  labels:
    app: loki
data:
  loki.yaml: |
    auth_enabled: {{ .Values.loki.config.auth_enabled }}
    server:
      http_listen_port: {{ .Values.loki.config.server.http_listen_port }}
    schema_config:
      configs:
        {{- range .Values.loki.config.schema_config.configs }}
        - from: {{ .from }}
          store: {{ .store }}
          object_store: {{ .object_store }}
          schema: {{ .schema }}
          index:
            prefix: {{ .index.prefix }}
            period: {{ .index.period }}
        {{- end }}
    storage_config:
      boltdb:
        directory: {{ .Values.loki.config.storage_config.boltdb.directory }}
      filesystem:
        directory: {{ .Values.loki.config.storage_config.filesystem.directory }}
