apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  labels:
    app: loki
  namespace: loki1
data:
  loki.yaml: |
    auth_enabled: false  # Disable authentication

    server:
      http_listen_port: 3100  # Port for HTTP API
      grpc_listen_port: 9095  # Port for gRPC
      log_level: info         # Log level (info, debug, etc.)

    ingester:
      wal:
        dir: /mnt/data/loki/wal  # Write-ahead log directory
      chunk_target_size: 1048576  # Target size for log chunks (1MB)
      max_chunk_age: 1h           # Maximum age of log chunks before they are flushed

    storage_config:
      boltdb_shipper:
        active_index_directory: /mnt/data/loki/index  # Index directory
        cache_location: /mnt/data/loki/cache          # Cache location
        shared_store: filesystem                     # Type of shared storage (filesystem, s3, gcs, etc.)
      filesystem:
        directory: /mnt/data/loki/storage  # Storage directory on the local filesystem

    chunk_store_config:
      max_look_back_period: 0s  # The maximum period Loki looks back for logs

    table_manager:
      retention_deletes_enabled: true  # Enable retention delete
      retention_period: 168h          # Retention period for logs (7 days)

    compactor:
      working_directory: /mnt/data/loki/compactor  # Directory for compactor to work
      shared_store: filesystem                     # Storage backend for compactor
      compaction_interval: 1h                      # Interval for compaction
