apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  labels:
    app: loki
data:
  loki.yaml: |
    auth_enabled: {{ .Values.loki.config.auth_enabled }}
    server:
      http_listen_port: {{ .Values.loki.config.server.http_listen_port }}
    schema_config:
      configs:
        - from: {{ .Values.loki.config.schema_config.configs | first | .from }}
          store: {{ .Values.loki.config.schema_config.configs | first | .store }}
          object_store: {{ .Values.loki.config.schema_config.configs | first | .object_store }}
          schema: {{ .Values.loki.config.schema_config.configs | first | .schema }}
          index:
            prefix: {{ .Values.loki.config.schema_config.configs | first | .index.prefix }}
            period: {{ .Values.loki.config.schema_config.configs | first | .index.period }}
    storage_config:
      boltdb:
        directory: {{ .Values.loki.config.storage_config.boltdb.directory }}
      filesystem:
        directory: {{ .Values.loki.config.storage_config.filesystem.directory }}
