apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: loki1
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.0
          args:
            - -config.file=/etc/loki/loki.yaml
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: /data/loki
      volumes:
        - name: config
          configMap:
            name: loki-config  # Ensure the ConfigMap exists
        - name: storage
          hostPath:
            path: /mnt/data/loki
            type: DirectoryOrCreate
