apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: loki1
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      initContainers:
        - name: init-wal
          image: busybox
          command: ["sh", "-c", "mkdir -p /mnt/data/loki && chown -R 10001:10001 /mnt/data/loki"]
          volumeMounts:
            - name: loki-storage
              mountPath: /mnt/data/loki
      containers:
        - name: loki
          image: grafana/loki:2.9.0
          args:
            - -config.file=/etc/loki/loki.yaml
          ports:
            - containerPort: 3100
              name: http
            - containerPort: 9095
              name: grpc
          volumeMounts:
            - name: loki-storage
              mountPath: /mnt/data/loki
            - name: loki-config
              mountPath: /etc/loki/loki.yaml  # Changed from /etc/loki
              subPath: loki.yaml              # Explicitly specify subPath
      volumes:
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-pvc
        - name: loki-config
          configMap:
            name: loki-config
            items:
              - key: loki.yaml
                path: loki.yaml
