apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: loki1
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        fsGroup: 10001         # Ensure Loki can access volume
        runAsUser: 10001       # Loki user ID
        runAsGroup: 10001
        runAsNonRoot: true     # Extra security
      initContainers:
        - name: fix-permissions
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              echo "[init] Fixing volume permissions..." && \
              mkdir -p /mnt/data/loki/{chunks,rules,wal,boltdb-shipper-cache,boltdb-shipper-active} && \
              chown -R 10001:10001 /mnt/data/loki && \
              chmod -R 770 /mnt/data/loki
          volumeMounts:
            - name: loki-storage
              mountPath: /mnt/data/loki
          securityContext:
            runAsUser: 0  # Run as root to change ownership
      containers:
        - name: loki
          image: grafana/loki:2.9.0
          args:
            - -config.file=/etc/loki/loki.yaml
          ports:
            - containerPort: 3100
              name: http
            - containerPort: 9095
              name: grpc
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: loki-storage
              mountPath: /mnt/data/loki
            - name: loki-config
              mountPath: /etc/loki/loki.yaml
              subPath: loki.yaml
      volumes:
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-pvc
        - name: loki-config
          configMap:
            name: loki-config
            items:
              - key: loki.yaml
                path: loki.yaml
