apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: loki1
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        fsGroup: 10001  # Ensures Loki user has permissions on volumes
      initContainers:
        - name: init-permissions
          image: busybox:1.35
          command:
            - sh
            - -c
            - >
              mkdir -p /mnt/data/loki/{chunks,rules,boltdb-shipper-active,boltdb-shipper-cache} &&
              chown -R 10001:10001 /mnt/data/loki
          volumeMounts:
            - name: loki-storage
              mountPath: /mnt/data/loki
      containers:
        - name: loki
          image: grafana/loki:2.9.0
          args:
            - -config.file=/etc/loki/loki.yaml
          ports:
            - containerPort: 3100
              name: http
            - containerPort: 9095
              name: grpc
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: loki-storage
              mountPath: /mnt/data/loki
            - name: loki-config
              mountPath: /etc/loki/loki.yaml
              subPath: loki.yaml
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
      volumes:
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-pvc
        - name: loki-config
          configMap:
            name: loki-config
            items:
              - key: loki.yaml
                path: loki.yaml
