apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: loki1
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        fsGroup: 10001           # This ensures files are owned by Loki's group
        runAsUser: 10001         # Non-root user for Loki
        runAsGroup: 10001        # Non-root group for Loki
        runAsNonRoot: true       # Ensures no containers run as root
      initContainers:
        - name: volume-permission-fix
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              echo "[init] Creating Loki directories..."
              mkdir -p /mnt/data/loki/{chunks,rules,wal,boltdb-shipper-cache,boltdb-shipper-active} && \
              chmod -R 775 /mnt/data/loki && \
              ls -la /mnt/data/loki
          securityContext:
            runAsUser: 10001      # Same as main container
            runAsGroup: 10001    # Same as main container
          volumeMounts:
            - name: loki-storage
              mountPath: /mnt/data/loki
      containers:
        - name: loki
          image: grafana/loki:2.9.0
          args:
            - -config.file=/etc/loki/loki.yaml
          ports:
            - containerPort: 3100
              name: http
            - containerPort: 9095
              name: grpc
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 45
            periodSeconds: 10
          volumeMounts:
            - name: loki-storage
              mountPath: /mnt/data/loki
            - name: loki-config
              mountPath: /etc/loki/loki.yaml
              subPath: loki.yaml
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-pvc
        - name: loki-config
          configMap:
            name: loki-config
            items:
              - key: loki.yaml
                path: loki.yaml
