apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    app: loki
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: {{ .Values.loki.service.port }}
      targetPort: 3100
  type: {{ .Values.loki.service.type }}
